apiVersion: v1
kind: Service
metadata:
  name: plivo-api-clusterip-service
spec:
  type: ClusterIP
  selector:
    component: plivo-api-clusterip-service
  ports:
    - port: 3000
      targetPort: 3000
